### ISSUE TITLE
Error when placing tokens on scene

### ISSUE THREAD

**Issue by MrPotatoZed** [MAClavell/Toggle-Snap-to-Grid#2]
I'm not sure if this is causing problems but just wanted to report that I'm seeing this error most of the time when I place tokens on a scene. Find the culprit points at TStG and disabling it fixes the errors. Tested with only TStG, libwrapper, and find the culprit active. Hosted on the foundry. 
![image](https://user-images.githubusercontent.com/85974617/158041334-bc336683-1a87-4ed5-abdc-b8e3496799c5.png)
Thanks for all of your work on this mod.

**Comment by MAClavell** [comment]
Issue has been fixed. Please update to v2.7.1

Release: https://github.com/MAClavell/Toggle-Snap-to-Grid/releases/tag/2.7.1

**Comment by MrPotatoZed** [comment]
Working great after the update. Thank you!
