### ISSUE TITLE
dropping waypoints with space bar also toggle game state

### ISSUE THREAD

**Issue by wmve** [MAClavell/Toggle-Snap-to-Grid#3]
steps to reproduce

1. enable Drag Ruler and Toggle Snap to Grid
2. reload
3. drag token, dropping waypoints with ruler.  

expected result: waypoints dropped on path without toggling game state.
actual result: game state toggles every time you hit space to drop a waypoint.

i'm hoping you or manuelVo (other developer) can fix this.

![image](https://user-images.githubusercontent.com/55966777/175828430-2bf52034-42c4-48fa-a65e-50eaf20bd1e6.png)

**Comment by MAClavell** [comment]
Could not reproduce this issue. ManuelVo might have fixed this a while ago on their end. Closing.
